services:
  - type: web
    name: umm-dashboard
    env: node
    rootDir: umm-dashboard-react
    buildCommand: git lfs install && git lfs pull && npm run render-build
    startCommand: npm run render-start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=460"
      - key: GIT_LFS_SKIP_SMUDGE
        value: "0" - type: web
    name: umm-dashboard
    env: node
    rootDir: umm-dashboard-react
    buildCommand: git lfs install && git lfs pull && npm run render-build
    startCommand: npm run render-start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: GIT_LFS_SKIP_SMUDGE
        value: "0"
